# Generated by Django 5.0 on 2024-01-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeuploads', '0002_jobdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='description',
            field=models.TextField(),
        ),
    ]
