# Generated by Django 5.0 on 2024-01-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeuploads', '0003_alter_jobdescription_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='mbti',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
