# Generated by Django 5.0 on 2024-01-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeuploads', '0004_jobdescription_mbti'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='mbti',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
